name: test

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: go build
      run: |
        go build
    - name: vaddy test
      run: |
        mkdir -p ~/ssh
        echo "${VADDY_PRIVATE_KEY}" > ~/ssh/key
        chmod 600 ~/ssh/key
        ./vaddy-example &
        ssh -o 'UserKnownHostsFile=/dev/null' -o 'StrictHostKeyChecking=no' -i ~/ssh/key -N -R 0.0.0.0:${VADDY_REMOTE_PORT}:${VADDY_YOUR_LOCAL_IP}:${VADDY_YOUR_LOCAL_PORT} portforward@pfd.vaddy.net &
      env:
        VADDY_PRIVATE_KEY: ${{ secrets.VADDY_PRIVATE_KEY }}
        VADDY_REMOTE_PORT: ${{ secrets.VADDY_REMOTE_PORT }}
        VADDY_YOUR_LOCAL_IP: ${{ secrets.VADDY_YOUR_LOCAL_IP }}
        VADDY_YOUR_LOCAL_PORT: ${{ secrets.VADDY_YOUR_LOCAL_PORT }}
        LISTEN_ADDR: ${{ secrets.VADDY_YOUR_LOCAL_IP }}:${{ secrets.VADDY_YOUR_LOCAL_PORT }}
